import type { StageConfig } from "./types";
import {
  MAZE_STAGE_1,
  MAZE_STAGE_2,
  MAZE_STAGE_3,
  MAZE_STAGE_4,
} from "./mazes";

export const STAGES: StageConfig[] = [
  {
    id: 1,
    title: "Ăn Gì?",
    subtitle: "Food district at night",
    theme: "warm",
    palette: {
      wall: 0xff6b4a,
      floor: 0x2a1520,
      accent: 0xffb347,
      glow: 0xff4466,
      particle: 0xffaa66,
    },
    ghostLabels: ["Đói", "Phân vân", "Ăn ở đâu?", "Hết bàn", "Menu stress"],
    centerGhostSlots: 1,
    ghostSpeed: 56,
    exits: [
      {
        id: "hotpot",
        label: "Hotpot",
        vibe: "social · bonding",
        color: "#ff4466",
      },
      { id: "bbq", label: "BBQ", vibe: "chaotic fun", color: "#ff8844" },
      {
        id: "ramen",
        label: "Ramen",
        vibe: "cozy · intimate",
        color: "#ffaa88",
      },
      {
        id: "softmeal",
        label: "Soft Meal",
        vibe: "calm · safe",
        color: "#ffe8c8",
      },
    ],
    maze: MAZE_STAGE_1,
  },
  {
    id: 2,
    title: "Hangout Ở Đâu?",
    subtitle: "Downtown nightlife",
    theme: "neon",
    palette: {
      wall: 0x9b5cff,
      floor: 0x12082a,
      accent: 0x5ce1ff,
      glow: 0xc77dff,
      particle: 0x88aaff,
    },
    ghostLabels: [
      "Im lặng",
      "Ex nhắn tin",
      "Lo âu",
      "Social pressure",
      "Bad vibe",
    ],
    centerGhostSlots: 1,
    ghostSpeed: 65,
    exits: [
      {
        id: "jazz",
        label: "Music Bar",
        vibe: "chemistry · flirty",
        color: "#c77dff",
      },
      { id: "pub", label: "Talking Pub", vibe: "deep talk", color: "#d4a574" },
      {
        id: "arcade",
        label: "Arcade",
        vibe: "playful chaos",
        color: "#5ce1ff",
      },
      {
        id: "books",
        label: "Book Store",
        vibe: "quiet comfort",
        color: "#aabbff",
      },
    ],
    maze: MAZE_STAGE_2,
  },
  {
    id: 3,
    title: "Dresscode",
    subtitle: "Magical wardrobe maze",
    theme: "fashion",
    palette: {
      wall: 0xff7eb9,
      floor: 0x1a1028,
      accent: 0x7ee8fa,
      glow: 0xffb3e6,
      particle: 0xa8f0ff,
    },
    ghostLabels: [
      "Overthink",
      "Quá effort?",
      "Tự ti",
      "Insecurity",
      "Mirror anxiety",
    ],
    centerGhostSlots: 1,
    ghostSpeed: 74,
    exits: [
      {
        id: "street",
        label: "Streetwear",
        vibe: "cool · confident",
        color: "#7ee8fa",
      },
      {
        id: "classy",
        label: "Lịch Sự",
        vibe: "mature · polished",
        color: "#c9b8ff",
      },
      {
        id: "retro",
        label: "Retro",
        vibe: "artistic · nostalgic",
        color: "#ff7eb9",
      },
      {
        id: "whatever",
        label: "Whatever",
        vibe: "chaotic honesty",
        color: "#e8e4ff",
      },
    ],
    maze: MAZE_STAGE_3,
  },
  {
    id: 4,
    title: "Đi Tới Mấy Giờ?",
    subtitle: "Night → dawn",
    theme: "night",
    palette: {
      wall: 0x6b8cff,
      floor: 0x0a1028,
      accent: 0xc0d8ff,
      glow: 0x88aaff,
      particle: 0xffeeaa,
    },
    ghostLabels: [
      "Sợ mở lòng",
      "Attachment",
      "Ý nghĩa gì?",
      "Fear",
      "Vulnerability",
    ],
    centerGhostSlots: 0,
    ghostSpeed: 84,
    exits: [
      {
        id: "midnight",
        label: "Midnight",
        vibe: "safe · controlled",
        color: "#6b8cff",
      },
      {
        id: "overnight",
        label: "Overnight",
        vibe: "intense · adventurous",
        color: "#aa66ff",
      },
      {
        id: "home",
        label: "Ăn Xong Về",
        vibe: "practical · distant",
        color: "#9ec8e8",
      },
      {
        id: "detour",
        label: "Nào cũng được",
        vibe: "magical connection",
        color: "#ffe08a",
      },
    ],
    maze: MAZE_STAGE_4,
  },
];
